CREATE TABLE IF NOT EXISTS matchs (
    id SERIAL PRIMARY KEY,
    match_cat_id INT REFERENCES cats(id) ON DELETE CASCADE,
    user_cat_id INT REFERENCES cats(id) ON DELETE CASCADE,
    has_matched BOOLEAN DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);